sudo: false
os: linux
language: php

php:
  - 7.1
  - 7.2
  - 7.3

branches:
  only:
    - master
    - /^\d+\.x$/
    - /^\d+\.\d+\.\d+$/

install:
  - composer install --prefer-dist

script:
  - make test
  - make analyse

after_success:
  - if [[ "7.3" == "${TRAVIS_PHP_VERSION}" ]]; then bash <(curl -s https://codecov.io/bash) ; fi
  - if [[ "7.3" == "${TRAVIS_PHP_VERSION}" ]]; then travis_retry php vendor/bin/codacycoverage clover ; fi

cache:
  directories:
    - $HOME/.composer/cache/files
    - vendor
